<!-- ?= $this->teste; //imprimir os dados recebidos ? -->
<form method='POST'>

	<label for='email'>Email:</label><input type='text' name='email' id='email'> <br />
	<label for='senha'>Senha:</label><input type='password' name='senha' id='senha'> <br />
	<input type='submit' value='Cadastrar'>

</form>

<br>

<a href="<?php echo $this->url(array('controller' => 'router', 
    'action' => 'index')); ?>">Voltar</a>